version: "3.9"

services:
  backend:
    build: ./backend
    container_name: prectice_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://onlineshope:onlineshope@cluster0.byso3zc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: prectice_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000/

  mongo:
    image: mongo:7
    container_name: my_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
